name: stability
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - expat=2.6.2
  - libffi=3.4.4
  - openssl=3.0.14
  - pip=24.0
  - python=3.12.4
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - ase==3.23.0
      - brokenaxes==0.6.1
      - colorama==0.4.6
      - contourpy==1.2.1
      - cycler==0.12.1
      - fonttools==4.53.1
      - imageio==2.34.2
      - iteround==1.0.4
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - matplotlib==3.9.1
      - numpy==2.0.0
      - packaging==24.1
      - pandas==2.2.2
      - pillow==10.4.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - six==1.16.0
      - threadpoolctl==3.5.0
      - tqdm==4.66.4
      - tzdata==2024.1
